[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXTJS_CACHE = "true"
  NODE_VERSION = "20"
  
  # Firebase config
  NEXT_PUBLIC_FIREBASE_API_KEY = "AIzaSyAOE02LUyPe9hzbzA6gfnYDysA2ar8VLsw"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "mehkova-86944.firebaseapp.com"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID = "mehkova-86944"
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "mehkova-86944.appspot.com"
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "596325574453"
  NEXT_PUBLIC_FIREBASE_APP_ID = "1:596325574453:web:701f70b5b500c8aaa90e7c"
  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID = "G-5FPF9H68E5"

# Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-eval' https://apis.google.com https://www.googletagmanager.com https://www.google-analytics.com;
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: https://*.googleapis.com https://*.gstatic.com;
      connect-src 'self' https://*.googleapis.com;
      font-src 'self' https://fonts.gstatic.com;
      frame-src https://*.firebaseapp.com;
    """
    Referrer-Policy = "strict-origin-when-cross-origin"

# Redirects
[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200