[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXTJS_CACHE = "true"
  NODE_VERSION = "20"
  
  # Firebase config (same as before)
  NEXT_PUBLIC_FIREBASE_API_KEY = "AIzaSyAOE02LUyPe9hzbzA6gfnYDysA2ar8VLsw"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "mehkova-86944.firebaseapp.com"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID = "mehkova-86944"
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "mehkova-86944.appspot.com"
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "596325574453"
  NEXT_PUBLIC_FIREBASE_APP_ID = "1:596325574453:web:701f70b5b500c8aaa90e7c"
  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID = "G-5FPF9H68E5"

  # Image optimization specific
  NEXT_PUBLIC_IMAGE_OPTIMIZATION_PROVIDER = "netlify" # Use Netlify's image CDN
  NEXT_PUBLIC_IMAGE_DOMAINS = "mehkova-86944.firebaseapp.com,mehkova-86944.appspot.com" # Add your Firebase storage domains

# Next.js plugin with image optimization
[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    enableNextJsImageComponent = true
    enableSharpImageOptimization = true

# Image CDN configuration
[[plugins]]
  package = "@netlify/plugin-image-optim"
  [plugins.inputs]
    compress = true
    webp = true
    avif = true
    quality = 80
    remoteImages = [
      "https://mehkova-86944.firebaseapp.com/*",
      "https://mehkova-86944.appspot.com/*"
    ]

# Custom headers for image optimization
[[headers]]
  for = "/_next/image/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    CDN-Cache-Control = "public, max-age=31536000, immutable"

# Security headers (updated for images)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-eval' https://apis.google.com https://www.googletagmanager.com https://www.google-analytics.com;
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: https://*.googleapis.com https://*.gstatic.com https://*.firebaseapp.com https://*.appspot.com;
      connect-src 'self' https://*.googleapis.com;
      font-src 'self' https://fonts.gstatic.com;
      frame-src https://*.firebaseapp.com;
    """
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

# Redirects
[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200